// <auto-generated />
using ActivityCenter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ActivityCenter.Migrations
{
    [DbContext(typeof(DojoActivityContext))]
    partial class DojoActivityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("ActivityCenter.Models.ActivityParticipant", b =>
                {
                    b.Property<int>("ActivityParticipantID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created_at");

                    b.Property<int>("DojoActivityID");

                    b.Property<DateTime>("Updated_at");

                    b.Property<int>("UserID");

                    b.HasKey("ActivityParticipantID");

                    b.HasIndex("DojoActivityID");

                    b.HasIndex("UserID");

                    b.ToTable("ActivityParticipants");
                });

            modelBuilder.Entity("ActivityCenter.Models.DojoActivity", b =>
                {
                    b.Property<int>("DojoActivityID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActivityDate");

                    b.Property<TimeSpan>("ActivityTime");

                    b.Property<DateTime>("Created_at");

                    b.Property<int>("CreatorID");

                    b.Property<string>("Description");

                    b.Property<int>("Duration");

                    b.Property<string>("HourOrMin");

                    b.Property<string>("Title");

                    b.Property<DateTime>("Updated_at");

                    b.Property<int?>("UserID");

                    b.HasKey("DojoActivityID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("UserID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("ActivityCenter.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created_at");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<DateTime>("Updated_at");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ActivityCenter.Models.ActivityParticipant", b =>
                {
                    b.HasOne("ActivityCenter.Models.DojoActivity", "DojoActivity")
                        .WithMany("Participants")
                        .HasForeignKey("DojoActivityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ActivityCenter.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ActivityCenter.Models.DojoActivity", b =>
                {
                    b.HasOne("ActivityCenter.Models.User", "Creator")
                        .WithMany("CreatedActivities")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ActivityCenter.Models.User")
                        .WithMany("JoinedActivities")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
